config/routes.rb
Rails.application.routes.draw do
  resources :characters, only: [:index, :show]
  resources :planets, only: [:index, :show]
  resources :species, only: [:index, :show]
  resources :theatres, only: [:index, :show]
  get '/about', to: 'about#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: redirect('/characters')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
    belongs_to :planet, foreign_key: "homeworld", primary_key: "planet_name"
    belongs_to :species, foreign_key: "species", primary_key: "species_name"

    validates :character_name, presence: true, uniqueness: true
    validates :height, :mass, numericality: true
end

app/models/planet.rb
class Planet < ApplicationRecord
    has_many :characters, foreign_key: 'homeworld', primary_key: 'planet_name'
    has_many :species, foreign_key: 'homeworld', primary_key: 'planet_name'

    validates :planet_name, presence: true, uniqueness: true
    validates :diameter, :surface_water, numericality: true
    validates :population, numericality: {only_integer: true}
end

app/models/species.rb
class Species < ApplicationRecord
    belongs_to :planet, foreign_key: "homeworld", primary_key: "planet_name"
    has_many :characters, foreign_key: 'species', primary_key: 'species_name'

    validates :species_name, presence: true, uniqueness: true
    validates :average_height, numericality: true
    validates :average_lifespan, numericality: {only_integer: true}
end

app/models/theatre.rb
class Theatre < ApplicationRecord
    def google_static_map_url
      base_url = 'https://maps.googleapis.com/maps/api/staticmap?'
  
      api_key = 'AIzaSyCQ0GfdaFveXjTzVzsxx6hKddP_2XAycns'
    
      latitude = self.latitude
      longitude = self.longitude
      zoom = 15
      size = '600x300'
    
      map_url = "#{base_url}center=#{latitude},#{longitude}&zoom=#{zoom}&size=#{size}&markers=#{latitude},#{longitude}&key=#{api_key}"
    
      map_url
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.includes(:planet, :species)
    
    @homeworlds = Set.new
    @species = Set.new

    @characters.each do |c|
      @homeworlds << c.planet.planet_name
      @sn = c.species&.species_name
      if @sn
        @species << @sn
      end
    end
    @homeworlds = @homeworlds.sort
    @species = @species.sort

    if params[:query].present? || params[:homeworld].present? || params[:species].present?
      @characters = @characters.where(
        "character_name LIKE ? AND homeworld LIKE ? AND species LIKE ?",
        "%#{params[:query]}%", "%#{params[:homeworld]}%", "%#{params[:species]}%")
    end

    @characters = @characters.page(params[:page]).per(10)
  end

  def show
    @character = Character.find(params[:id])
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
    @planets = @planets.where("planet_name LIKE ?", "%#{params[:query]}%") if params[:query].present?
    @planets = @planets.page(params[:page]).per(10)
  end

  def show
    @planet = Planet.find(params[:id])
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.includes(:planet, :characters)

    @homeworlds = Set.new

    @species.each do |s|
      @homeworlds << s.planet.planet_name
    end
    @homeworlds = @homeworlds.sort
    
    if params[:query].present? || params[:homeworld].present?
      @species = @species.where(
        "species_name LIKE ? AND homeworld LIKE ?",
        "%#{params[:query]}%", "%#{params[:homeworld]}%")
    end

    @species = @species.page(params[:page]).per(10)
  end

  def show
    @specie = Species.find(params[:id])
  end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  def index
    @theatres = Theatre.all
    @theatres = @theatres.where("name LIKE ?", "%#{params[:query]}%") if params[:query].present?
    @theatres = @theatres.page(params[:page]).per(10)
  end

  def show
    @theatre = Theatre.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/about/index.html.erb
<%= stylesheet_link_tag 'application' %>
<h1>About</h1>

<div>
    <div>
        <p>
            I am going to use data from a Star Wars dataset found on Kaggle.com (https://www.kaggle.com/datasets/jsphyg/star-wars?resource=download). This data set contains information about Star Wars Universe such as its planets, characters, species, vehicles(not going to use) and starships(not going to use). The data is in CSV format.
        </p>
    </div>
    <div>
        <div>
            <h3>Planets:</h3>
            <p>
                This data contains information about the Planets in Star Wars, and I will be using columns such as the planet's name, diameter, climate, gravity, terrain, surface water and population. This data will be put inside a table called Planets.
            </p>
        </div>
        <div>
            <h3>Characters:</h3>
            <p>
                This data contains information about the Characters in Star Wars, and I will be using columns such as their name, height, mass, hair color, skin color, eye color, birth year/age, gender, homeworld and species. This data will be put inside a table called Characters.
            </p>
        </div>
        <div>
            <h3>Species:</h3>
            <p>
                This data contains information about the Species in Star Wars, and I will be using columns such as the sepecies' name, classification, average height, skin color, hair color, eye color, average lifespan, language and homeworld. This data will be put inside a table called Species.
            </p>
        </div>
    </div>
    <div>
        <p>
            The Planets can have zero or many Characters.<br>
            The Planets can have zero or many Species.<br>
            The Characters can have 1 Planet(homeworld, NA if unknown).<br>
            The Characters can have 1 Species (NA if unknown).<br>
            The Species can have zero or many Characters.<br>
            The Species can have 1 Planet(homeworld, NA if unknown).
        </p>
        <p>
            Planets PK = name<br>
            Characters PK = name<br>
            Species PK = name
        </p>
    </div>
    <div>
        <img src="/ruby_erd.png" alt="erd for project data">
    </div>
</div>

app/views/characters/index.html.erb
<h1>Characters</h1>
<%= paginate @characters %>
<ul>
    <% @characters.each do |character| %>
        <li>
            <h3>
                <%= link_to character.character_name, character_path(character) %>
            </h3>
        </li>
    <% end %>
</ul>

app/views/characters/show.html.erb
<h1><%= @character.character_name %></h1>
<div>
    <p>Height: <%= @character.height %></p>
    <p>Mass: <%= @character.mass %></p>
    <p>Hair Color: <%= @character.hair_color %></p>
    <p>Skin Color: <%= @character.skin_color %></p>
    <p>Eye Color: <%= @character.eye_color %></p>
    <p>Birth Year: <%= @character.birth_year %></p>
    <p>Gender: <%= @character.gender %></p>
    <p>Homeworld: <%= link_to @character.planet.planet_name, planet_path(@character.planet) %></p>
    <% if @character.species %>
        <p>Species: <%= link_to @character.species.species_name, species_path(@character.species) %></p>
    <% else %>
        <p>Species: Unknown</p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StefanRubyIntroProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'shared/menu' %>
        <div class="top-level-search">
          <% if current_page?(action: 'index') && !current_page?(controller: 'about') %>
            <div class="top-level-search">
              <form action="<%= request.original_url %>" method="get" class="search-form">
                <div class="control">
                  <input class="input" name="query" type="text" placeholder="Search" value="<%= params[:query] %>">
                </div>
                  <% if current_page?(controller: 'characters') %>
                    <select class="select" name="homeworld" style="height: 200px; overflow-y: auto;">
                      <option value="">- search by homeworld -</option>
                      <% @homeworlds.each do |homeworld| %>
                        <option value="<%= homeworld %>" <%= 'selected' if params[:homeworld] == homeworld %>>
                          <%= homeworld %>
                        </option>
                      <% end %>
                    </select>
                    <select class="select" name="species" style="height: 200px; overflow-y: auto;">
                      <option value="">- search by species -</option>
                      <% @species.each do |specie| %>
                        <option value="<%= specie %>" <%= 'selected' if params[:species] == specie %>>
                          <%= specie %>
                        </option>
                      <% end %>
                    </select>
                  <% end %>

                  <% if current_page?(controller: 'species') %>
                    <select class="select" name="homeworld" style="height: 200px; overflow-y: auto;">
                      <option value="">- search by homeworld -</option>
                      <% @homeworlds.each do |homeworld| %>
                        <option value="<%= homeworld %>" <%= 'selected' if params[:homeworld] == homeworld %>>
                          <%= homeworld %>
                        </option>
                      <% end %>
                    </select>
                  <% end %>
                  <button type="submit" class="button is-primary" style="background-color: rgb(41, 33, 33);;">
                    Search
                  </button>
                </form>
              </div>
              <div>
                <form action="<%= request.original_url %>" method="get">
                    <button type="submit" class="button is-secondary">
                      Reset
                    </button>
                </form>
              </div>
          <% end %>
        </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/planets/index.html.erb
<h1>Planets</h1>
<%= paginate @planets %>
<ul>
    <% @planets.each do |planet| %>
        <li>
            <h3>
                <%= link_to planet.planet_name, planet_path(planet) %>
            </h3>
        </li>
    <% end %>
</ul>

app/views/planets/show.html.erb
<h1><%= @planet.planet_name %></h1>
<div>
    <p>Diameter: <%= @planet.diameter %></p>
    <p>Climate: <%= @planet.climate %></p>
    <p>Gravity: <%= @planet.gravity %></p>
    <p>Terrain: <%= @planet.terrain %></p>
    <p>Surface Water: <%= @planet.surface_water %></p>
    <p>Population: <%= @planet.population %></p>
    <p>Species from <%= @planet.planet_name %>:
        <% @planet.species.each_with_index do |specie, index| %>
            <%= link_to specie.species_name, species_path(specie) %><% if index < @planet.species.size-1 %>,<% end %>
        <% end %>
    </p>
    <p>Characters from <%= @planet.planet_name %>:
        <% @planet.characters.each_with_index do |character, index| %>
            <%= link_to character.character_name, character_path(character) %><% if index < @planet.characters.size-1 %>,<% end %>
        <% end %>
    </p>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="<%= characters_path %>">
        Characters
      </a>
      <a class="navbar-item" href="<%= species_index_path %>">
        Species
      </a>
      <a class="navbar-item" href="<%= planets_path %>">
        Planets
      </a>
      <a class="navbar-item" href="<%= theatres_path %>">
        Where could I see these things?
      </a>
      <a class="navbar-item" href="<%= about_path %>">
        About
      </a>
    </div>
  </div>
</nav>

app/views/species/index.html.erb
<h1>Species</h1>
<%= paginate @species %>
<ul>
    <% @species.each do |specie| %>
        <li>
            <h3>
                <%= link_to specie.species_name, species_path(specie) %>
            </h3>
        </li>
    <% end %>
</ul>

app/views/species/show.html.erb
<h1><%= @specie.species_name %></h1>
<div>
    <p>Classification: <%= @specie.classification %></p>
    <p>Average_height: <%= @specie.average_height %></p>
    <p>Skin Color: <%= @specie.skin_color %></p>
    <p>Hair Color: <%= @specie.hair_color %></p>
    <p>Eye Color: <%= @specie.eye_color %></p>
    <p>Average Lifespan: <%= @specie.average_lifespan %></p>
    <p>Language: <%= @specie.language %></p>
    <p>Homeworld: <%= link_to @specie.planet.planet_name, planet_path(@specie.planet) %></p>
    <p>Characters who are <%= @specie.species_name %>:
        <% @specie.characters.each_with_index do |character, index| %>
            <%= link_to character.character_name, character_path(character) %><% if index < @specie.characters.size-1 %>,<% end %>
        <% end %>
    </p>
</div>

app/views/theatres/index.html.erb
<h1>Theatres</h1>
<%= paginate @theatres %>
<ul>
    <% @theatres.each do |theatre| %>
        <li>
            <h3>
                <%= link_to theatre.name, theatre_path(theatre) %>
            </h3>
        </li>
    <% end %>
</ul>

app/views/theatres/show.html.erb
<h1><%= @theatre.name %></h1>
<div>
    <p>Address: <%= @theatre.address %>, <%= @theatre.city %>, <%= @theatre.province %></p>

    <img src="<%= @theatre.google_static_map_url %>" alt="Map of <%= @theatre.name %>">
</div>